Allow specification of number of partitions in XShards.partition
intel-analytics/analytics-zoo pull request #3467
Opened 2021-02-04 12:29 UTC by GZHoffie

I added a parameter `num_shards` that allows user to specify number of partitions in the `XShards.partition` function, so that the issue #3466 can be resolved by changing the code to
```python
sample_shards = XShards.partition({"x": sampled}, num_shards=1)
```
so that there is no empty shards. Do I need to add a warning message if there is empty shard?

2021-02-05 02:39 UTC, yangw1234 commented
raise an error if `length` is smaller than the number of shards?

2021-02-05 02:40 UTC, yangw1234 commented
also need unit tests

2021-02-05 13:22 UTC, GZHoffie commented
http://10.239.47.210:18888/job/ZOO-PR-Validation/5044/ Most builds shows that build is success, but with the following errors
```
PEP8 checks failed.
./zoo/examples/orca/learn/horovod/pytorch_estimator.py:120:101: E501 line too long (101 > 100 characters)
./zoo/examples/orca/learn/horovod/pytorch_estimator.py:131:101: E501 line too long (111 > 100 characters)
./zoo/examples/orca/learn/horovod/pytorch_estimator.py:133:101: E501 line too long (117 > 100 characters)
./zoo/examples/orca/learn/horovod/pytorch_estimator.py:135:101: E501 line too long (115 > 100 characters)
./zoo/examples/orca/learn/horovod/pytorch_estimator.py:137:101: E501 line too long (106 > 100 characters)
./zoo/examples/orca/learn/horovod/pytorch_estimator.py:139:19: E128 continuation line under-indented for visual indent
./zoo/examples/orca/learn/horovod/pytorch_estimator.py:140:19: E128 continuation line under-indented for visual indent
./zoo/examples/orca/learn/horovod/pytorch_estimator.py:141:19: E128 continuation line under-indented for visual indent
./zoo/examples/orca/learn/horovod/pytorch_estimator.py:142:19: E128 continuation line under-indented for visual indent
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```
the tests failed. I guess this is not related to my PR and will check later for solutions.

2021-02-07 06:21 UTC, yangw1234 commented
you need to add one or more unit tests to cover this case.

2021-02-07 06:22 UTC, yangw1234 requested changes
unit tests needed

2021-02-07 06:57 UTC, yangw1234 commented on pyzoo/zoo/orca/data/shard.py
> +        total_core_num = node_num * core_num if num_shards is None else num_shards
change `total_core_num` to something else, like "shard_num"

2021-02-07 06:57 UTC, yangw1234 commented on pyzoo/zoo/orca/data/shard.py
> +            assert data_length >= total_core_num, "The length of data {} is smaller than " \
where this `data_length` is defined?

2021-02-07 07:02 UTC, yangw1234 commented on pyzoo/zoo/orca/data/shard.py
> +                "at most {}.".format(data.shape[0], total_core_num, data.shape[0])
"at least"?

2021-02-07 07:03 UTC, GZHoffie commented on pyzoo/zoo/orca/data/shard.py
> +            assert data_length >= total_core_num, "The length of data {} is smaller than " \
Sorry, it's a copy mistake... Should be `data.shape[0]`

2021-02-07 07:07 UTC, GZHoffie commented on pyzoo/zoo/orca/data/shard.py
> +                "at most {}.".format(data.shape[0], total_core_num, data.shape[0])
Should be at most? If number of shards is too large then there will be empty shards.

Do we need to check empty shards here or in the tf_runner?

2021-02-07 08:15 UTC, yangw1234 commented on pyzoo/zoo/orca/data/shard.py
> +                "at most {}.".format(data.shape[0], total_core_num, data.shape[0])
yeah, ok

2021-02-07 08:16 UTC, yangw1234 approved these changes

2021-02-08 07:24 UTC, GZHoffie commented
Jenkins passed http://10.239.47.210:18888/job/ZOO-PR-Validation/5061/, the case `ZOO-PR-Validation-Spark-2.4` is run again and passed here http://10.239.47.210:18888/job/ZOO-PR-Validation-Spark-2.4/3419/

2021-02-09 06:26 UTC, merged