Fix the error message of tsdata call sequence
intel-analytics/analytics-zoo pull request #4244
Opened 2021-07-08 10:34 UTC by liangs6212

2021-07-08 10:35 UTC, liangs6212 commented
#4100

2021-07-09 02:28 UTC, TheaperDeng commented on pyzoo/zoo/chronos/data/tsdataset.py
> +from sklearn.utils.validation import check_is_fitted
I think you can move this import to line 520 (right before your calling). This **may** prevent some version issue in the future.

2021-07-12 03:09 UTC, TheaperDeng commented on pyzoo/zoo/chronos/data/tsdataset.py
> +            gen_rolling do not need to be called multiple times, please remove redundant calls."
"Only one of gen_global_feature and gen_rolling_feature should be called."

2021-07-12 03:09 UTC, TheaperDeng commented on pyzoo/zoo/chronos/data/tsdataset.py
> +        self._feature_generation_completed = False
self._has_generate_agg_feature

2021-07-12 03:09 UTC, TheaperDeng commented on pyzoo/zoo/chronos/data/tsdataset.py
> +            gen_rolling do not need to be called multiple times, please remove redundant calls."
"Only one of gen_global_feature and gen_rolling_feature should be called."

2021-07-12 03:09 UTC, TheaperDeng commented on pyzoo/zoo/chronos/data/tsdataset.py
> +        self.roll_addtional_feature = None
additional

2021-07-13 01:18 UTC, TheaperDeng approved these changes
LGTM, pls run jenkins

2021-07-14 06:31 UTC, liangs6212 commented
http://10.239.176.111:18888/job/ZOO-PR-Python-ExampleTests-py37-ray-horovod-Spark3/1500/
http://10.239.176.111:18888/job/ZOO-PR-Validation/6079/

2021-07-15 07:06 UTC, TheaperDeng requested changes

2021-07-15 07:06 UTC, TheaperDeng commented on pyzoo/test/zoo/chronos/data/test_tsdataset.py
> +            tsdata._check_basic_invariants()
add a test for call both `gen_global` and `gen_rolling`.

2021-07-15 07:06 UTC, TheaperDeng commented on pyzoo/zoo/chronos/data/tsdataset.py
> +                "When calling scale for the first time, you need to set fit=True."
I think the prev one is better? This one is kind of "hacking"

2021-07-15 07:31 UTC, liangs6212 commented on pyzoo/zoo/chronos/data/tsdataset.py
> +                "When calling scale for the first time, you need to set fit=True."
Has become our shape.

2021-07-26 05:53 UTC, TheaperDeng approved these changes
LGTM, pls run jenkins

2021-07-29 09:23 UTC, liangs6212 commented
http://10.112.231.51:18888/job/ZOO-PR-Python-Spark-3.0-py37-ray/1641/
http://10.112.231.51:18888/job/ZOO-PR-Python-ExampleTests/3475/
http://10.112.231.51:18888/job/ZOO-PR-Scala-StyleCheck/6270/
http://10.112.231.51:18888/job/ZOO-PR-Python-Spark-2.4-py37-ray/2439/
http://10.112.231.51:18888/job/ZOO-PR-Python-Spark-2.3-py37/3005/
http://10.112.231.51:18888/job/ZOO-PR-Validation/6169/

2021-08-02 09:41 UTC, liangs6212 commented
http://10.112.231.51:18888/job/ZOO-PR-Validation/6193/
http://10.112.231.51:18888/job/ZOO-PR-Python-Spark-3.1-py36k216/1635/
http://10.112.231.51:18888/job/ZOO-PR-Python-Spark-3.1-py36-ray/1642/

2021-08-03 01:28 UTC, merged